wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_accuracy
      5: 1
      6:
      - 1
    - 1: train_f1_score_micro
      5: 1
      6:
      - 1
    - 1: train_f1_score_macro
      5: 1
      6:
      - 1
    - 1: train_AUC_0
      5: 1
      6:
      - 1
    - 1: train_AUC_1
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: validation_loss_step/epoch_0
      5: 1
      6:
      - 1
    - 1: validation_loss_epoch
      5: 1
      6:
      - 1
    - 1: validation_accuracy
      5: 1
      6:
      - 1
    - 1: validation_f1_score_micro
      5: 1
      6:
      - 1
    - 1: validation_f1_score_macro
      5: 1
      6:
      - 1
    - 1: validation_AUC_0
      5: 1
      6:
      - 1
    - 1: validation_AUC_1
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: validation_loss_step/epoch_1
      5: 1
      6:
      - 1
    - 1: validation_loss_step/epoch_2
      5: 1
      6:
      - 1
    python_version: 3.8.8
    start_time: 1647819592
    t:
      1:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      3:
      - 7
      4: 3.8.8
      5: 0.12.11
      8:
      - 5
