wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1647862520
    t:
      1:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      4: 3.8.8
      5: 0.12.11
      8:
      - 5
