wandb_version: 1

AL_method:
  desc: null
  value: uncertainty-margin
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1648628242
    t:
      1:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      2:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      3:
      - 2
      - 19
      4: 3.8.8
      5: 0.12.11
      8:
      - 5
add_val_to_train:
  desc: null
  value: false
batch_size:
  desc: null
  value: 128
concat:
  desc: null
  value: true
dataset:
  desc: null
  value: politifact
gpus_available:
  desc: null
  value:
  - 3
lr:
  desc: null
  value: 0.005
model:
  desc: null
  value: gcnfn
nb_samples:
  desc: null
  value: 1
nhid:
  desc: null
  value: 128
num_classes:
  desc: null
  value: 2
number_AL_iteration:
  desc: null
  value: 30
retrain_from_scratch:
  desc: null
  value: true
tot_num_checked_urls:
  desc: null
  value: 1200
train_last_samples:
  desc: null
  value: .inf
training_years:
  desc: null
  value:
  - 2005
  - 2021
val_last_samples:
  desc: null
  value: .inf
warm_start_years:
  desc: null
  value:
  - .inf
  - .inf
weight_decay:
  desc: null
  value: 0.01
workers_available:
  desc: null
  value: 3
