wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_accuracy
      5: 1
      6:
      - 1
    - 1: train_f1_score_micro
      5: 1
      6:
      - 1
    - 1: train_f1_score_macro
      5: 1
      6:
      - 1
    - 1: train_AUC
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: validation_loss
      5: 1
      6:
      - 1
    - 1: validation_accuracy
      5: 1
      6:
      - 1
    - 1: validation_f1_score_micro
      5: 1
      6:
      - 1
    - 1: validation_f1_score_macro
      5: 1
      6:
      - 1
    - 1: validation_AUC
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
    - 1: test_accuracy
      5: 1
      6:
      - 1
    - 1: test_f1_score_micro
      5: 1
      6:
      - 1
    - 1: test_f1_score_macro
      5: 1
      6:
      - 1
    - 1: test_AUC
      5: 1
      6:
      - 1
    python_version: 3.8.8
    start_time: 1647864538
    t:
      1:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      2:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      3:
      - 2
      - 7
      4: 3.8.8
      5: 0.12.11
      8:
      - 5
