wandb_version: 1

.AL_params/AL_method:
  desc: null
  value: random
.data_params/dataname:
  desc: null
  value: gossipcop
.model_params/graph_model_name:
  desc: null
  value: gcn
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1648505191
    t:
      1:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      2:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      3:
      - 2
      4: 3.8.8
      5: 0.12.11
      8:
      - 5
