wandb_version: 1

AL_method:
  desc: null
  value: random
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1648675125
    t:
      1:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      4: 3.8.8
      5: 0.12.11
      8:
      - 5
dataset:
  desc: null
  value: gossipcop
model:
  desc: null
  value: gat
