wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.8
    start_time: 1648204778
    t:
      1:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      2:
      - 1
      - 5
      - 9
      - 40
      - 41
      - 50
      3:
      - 7
      - 13
      4: 3.8.8
      5: 0.12.11
      8:
      - 5
args/batch_size:
  desc: null
  value: 128
args/concat:
  desc: null
  value: true
args/device:
  desc: null
  value: cuda:0
args/dropout_ratio:
  desc: null
  value: 0.0
args/epochs:
  desc: null
  value: 30
args/feature:
  desc: null
  value: bert
args/lr:
  desc: null
  value: 0.001
args/model:
  desc: null
  value: gat
args/multi_gpu:
  desc: null
  value: false
args/nhid:
  desc: null
  value: 128
args/num_classes:
  desc: null
  value: 2
args/num_features:
  desc: null
  value: 768
args/weight_decay:
  desc: null
  value: 0.01
concat:
  desc: null
  value: true
